In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\THIS\Downloads\final_dataset.csv")

In [3]:
df.shape

(33600, 23)

In [4]:
df.head(2)

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0
1,tt0073629,The Rocky Horror Picture Show,https://www.imdb.com/title/tt0073629,1975,1h 40m,R,7.4,173K,1200000.0,115798478.0,...,"[""Richard O'Brien"", 'Jim Sharman']","['Tim Curry', 'Susan Sarandon', 'Barry Bostwick']","['Dark Comedy', 'Raunchy Comedy', 'Rock Musica...","['United Kingdom', 'United States']","['Oakley Court, Windsor Road, Oakley Green, Wi...","['Twentieth Century Fox', 'Michael White Produ...",['English'],0,4,0

In [5]:
df.isnull().sum()

id                           0
Title                        0
Movie Link                   0
Year                         0
Duration                   221
MPA                       7976
Rating                     138
Votes                      138
budget                   21785
grossWorldWide           15378
gross_US_Canada          16029
opening_weekend_Gross    18077
directors                  359
writers                   1576
stars                      473
genres                     382
countries_origin           366
filming_locations         6729
production_companies      1378
Languages                  474
wins                         0
nominations                  0
oscars                       0
dtype: int64

In [8]:
df = df.ffill()

In [9]:
df.isnull().sum()

id                       0
Title                    0
Movie Link               0
Year                     0
Duration                 0
MPA                      0
Rating                   0
Votes                    0
budget                   0
grossWorldWide           0
gross_US_Canada          0
opening_weekend_Gross    0
directors                0
writers                  0
stars                    0
genres                   0
countries_origin         0
filming_locations        0
production_companies     0
Languages                0
wins                     0
nominations              0
oscars                   0
dtype: int64

In [10]:
df.head(1)

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0

In [15]:
df.Duration[:3]

0     2h 4m
1    1h 40m
2    2h 13m
Name: Duration, dtype: object

In [16]:
df.Votes

0        683K
1        173K
2        1.1M
3        279K
4         15K
         ...
33595    1.1K
33596      12
33597    1.3K
33598     337
33599     737
Name: Votes, Length: 33600, dtype: object

In [20]:
df.Votes.unique()

array(['683K', '173K', '1.1M', ..., '901K', '557K', '977K'],
      shape=(1758,), dtype=object)

In [72]:
def convertVotes( val ):
    val = str(val)
    if val[-1]=='K':
        return int(float(val[0:len(val)-1])*1000)
    elif val[-1]=='M':
        return int(float(val[0:len(val)-1])*1000000)
    else:
        return int(val)

In [79]:
convertVotes('2.5M')

2500000

In [80]:
df.Votes = df.Votes.map(convertVotes)

In [81]:
df.Votes

0         683000
1         173000
2        1100000
3         279000
4          15000
          ...
33595       1100
33596         12
33597       1300
33598        337
33599        737
Name: Votes, Length: 33600, dtype: int64

In [82]:
df.Votes.mean()

np.float64(30040.453154761904)

In [83]:
df.Duration

0         2h 4m
1        1h 40m
2        2h 13m
3         2h 5m
4        1h 50m
          ...
33595     2h 7m
33596    1h 25m
33597    1h 31m
33598    1h 30m
33599    1h 18m
Name: Duration, Length: 33600, dtype: object

In [84]:
df.Duration.unique()

array(['2h 4m', '1h 40m', '2h 13m', '2h 5m', '1h 50m', '1h 53m', '2h 16m',
       '1h 51m', '1h 57m', '1h 58m', '1h 47m', '1h 25m', '1h 37m',
       '2h 1m', '2h 9m', '1h 59m', '1h 44m', '2h 40m', '1h 39m', '1h 31m',
       '1h 46m', '2h 6m', '1h 24m', '1h 55m', '1h 35m', '1h 49m',
       '1h 56m', '1h 48m', '1h 36m', '3h 5m', '1h 20m', '1h 29m',
       '1h 38m', '1h 28m', '2h 7m', '3h 22m', '1h 30m', '1h 27m',
       '1h 33m', '2h 22m', '1h 45m', '2h 42m', '2h 24m', '2h 20m',
       '1h 23m', '2h 54m', '1h 52m', '1h 42m', '2h', '2h 2m', '1h 34m',
       '1h 32m', '1h 15m', '2h 12m', '1h 43m', '2h 32m', '1h 41m',
       '1h 14m', '1h 26m', '2h 26m', '2h 15m', '2h 30m', '2h 10m',
       '1h 22m', '1h 16m', '1h 21m', '1h 13m', '53m', '1h 19m', '3h 50m',
       '2h 38m', '2h 25m', '2h 43m', '2h 50m', '2h 36m', '1h 1m',
       '1h 18m', '2h 39m', '2h 19m', '1h 7m', '2h 11m', '1h 54m',
       '1h 17m', '1h 9m', '2h 3m', '2h 33m', '2h 57m', '1h 3m', '2h 35m',
       '2h 23m', '1h 12m', '2h 18m', '2h 55m', '2h 8m', '2h 45m', '4h',
       '2h 17m', '1h 10m', '3h 4m', '1h 11m', '1h 6m', '1h 8m', '2h 49m',
       '2h 41m', '7h 22m', '1h 5m', '1h 2m', '2h 29m', '56m', '3h',
       '2h 46m', '3h 53m', '2h 48m', '3h 2m', '2h 21m', '3h 30m',
       '2h 58m', '3h 9m', '2h 14m', '2h 56m', '59m', '2h 53m', '1h',
       '48m', '2h 52m', '2h 28m', '55m', '50m', '2h 44m', '2h 34m', '47m',
       '2h 27m', '2h 51m', '3h 11m', '3h 8m', '3h 3m', '3h 40m', '3h 14m',
       '4h 15m', '2h 31m', '57m', '45m', '52m', '2h 37m', '2h 47m',
       '3h 58m', '3h 17m', '4h 11m', '3h 52m', '4h 12m', '3h 36m',
       '1h 4m', '3h 13m', '3h 1m', '3h 18m', '2h 59m', '3h 49m', '3h 7m',
       '49m', '51m', '4h 30m', '3h 12m', '3h 6m', '3h 10m', '54m', '46m',
       'PG-13', '3h 39m', '3h 33m', '3h 15m', '58m', '3h 21m', '3h 35m',
       '4h 47m', '3h 57m', '43m', '3h 34m', '5h 35m', '3h 19m', '5h 10m',
       '3h 55m', '4h 20m', '5h 20m', '25h', '5h 57m', '87h', '40m',
       '3h 47m', '3h 25m', '3h 27m', '3h 16m', '3h 20m', '3h 41m',
       '3h 44m', '48h', '5h 19m', '4h 6m', '5h 17m', '4h 4m', '4h 10m',
       '3h 26m', '3h 24m', 'PG', '5h 16m', '5h 23m', '4h 48m', '3h 37m',
       '4h 2m', '44m', '4h 44m', '9h 26m', '3h 59m', '8h 5m', '5h 21m',
       '6h 33m', '3h 54m', '4h 7m', '6h 38m', '6h 14m', 'TV-G', '3h 28m',
       '4h 14m', '4h 18m', 'X', '5h 25m', 'TV-14', '5h 45m', '7h 19m',
       '12h 56m', '3h 23m'], dtype=object)

In [85]:
# Duration =>   1h 37m , 34m , 2h , TV-14

In [134]:
def convertDuration(val):
    if len(val.split())==2:
        li = val.split()
        return int(li[0][0:len(li[0])-1])*60 + int(li[1][0:len(li[1])-1])
    elif val[-1]=='m':
        return int(val[0:len(val)-1])
    elif val[-1]=='h':
        return int(val[0:len(val)-1])*60
    else:
        return convertDuration(df.Duration.mode()[0])

In [138]:
convertDuration('3h 34m')

214

In [139]:
df.Duration = df.Duration.map(convertDuration)

In [140]:
df.head(2)

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,124,PG,8.1,683000,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0
1,tt0073629,The Rocky Horror Picture Show,https://www.imdb.com/title/tt0073629,1975,100,R,7.4,173000,1200000.0,115798478.0,...,"[""Richard O'Brien"", 'Jim Sharman']","['Tim Curry', 'Susan Sarandon', 'Barry Bostwick']","['Dark Comedy', 'Raunchy Comedy', 'Rock Musica...","['United Kingdom', 'United States']","['Oakley Court, Windsor Road, Oakley Green, Wi...","['Twentieth Century Fox', 'Michael White Produ...",['English'],0,4,0

In [141]:
df.Duration

0        124
1        100
2        133
3        125
4        110
        ...
33595    127
33596     85
33597     91
33598     90
33599     78
Name: Duration, Length: 33600, dtype: int64

In [142]:
df.Duration.mean()

np.float64(103.10729166666667)