In [10]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\this\appdata\roaming\python\python314\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\this\appdata\roaming\python\python314\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\this\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\this\appdata\roaming\python\python314\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\this\appdata\roaming\python\python314\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\this\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
# If you want to load an excel
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\this\appdata\roaming\python\python314\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\this\appdata\roaming\python\python314\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
data = {
    'empid':[101,102,103,104,105,106,107,108],
    'empname':['Raju','Raman','Siya','Simran','Yogesh','Ravi','Mahesh','Vikas'],
    'empsal':[24565,78656,36654,87686,13324,67545,15263,21355]
}

In [14]:
print(data)

{'empid': [101, 102, 103, 104, 105, 106, 107, 108], 'empname': ['Raju', 'Raman', 'Siya', 'Simran', 'Yogesh', 'Ravi', 'Mahesh', 'Vikas'], 'empsal': [24565, 78656, 36654, 87686, 13324, 67545, 15263, 21355]}

In [15]:
data

{'empid': [101, 102, 103, 104, 105, 106, 107, 108],
 'empname': ['Raju',
  'Raman',
  'Siya',
  'Simran',
  'Yogesh',
  'Ravi',
  'Mahesh',
  'Vikas'],
 'empsal': [24565, 78656, 36654, 87686, 13324, 67545, 15263, 21355]}

In [17]:
# With pandas you can work on Series(1D) , DataFrames(2D - Tabular Format)

In [19]:
import pandas as pd

In [20]:
emp = pd.DataFrame(data)

In [21]:
emp

   empid empname  empsal
0    101    Raju   24565
1    102   Raman   78656
2    103    Siya   36654
3    104  Simran   87686
4    105  Yogesh   13324
5    106    Ravi   67545
6    107  Mahesh   15263
7    108   Vikas   21355

In [22]:
emp.empid

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
Name: empid, dtype: int64

In [23]:
emp.empname

0      Raju
1     Raman
2      Siya
3    Simran
4    Yogesh
5      Ravi
6    Mahesh
7     Vikas
Name: empname, dtype: object

In [25]:
emp.head()

   empid empname  empsal
0    101    Raju   24565
1    102   Raman   78656
2    103    Siya   36654
3    104  Simran   87686
4    105  Yogesh   13324

In [26]:
emp.head(2)

   empid empname  empsal
0    101    Raju   24565
1    102   Raman   78656

In [27]:
emp.tail()

   empid empname  empsal
3    104  Simran   87686
4    105  Yogesh   13324
5    106    Ravi   67545
6    107  Mahesh   15263
7    108   Vikas   21355

In [28]:
emp.tail(2)

   empid empname  empsal
6    107  Mahesh   15263
7    108   Vikas   21355

In [29]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   empid    8 non-null      int64
 1   empname  8 non-null      object
 2   empsal   8 non-null      int64
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes

In [30]:
emp.empsal

0    24565
1    78656
2    36654
3    87686
4    13324
5    67545
6    15263
7    21355
Name: empsal, dtype: int64

In [31]:
emp.empsal.sum()

np.int64(345048)

In [32]:
emp.empsal.mean()

np.float64(43131.0)

In [33]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\this\appdata\roaming\python\python314\site-packages (2.4.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
import numpy as np

In [63]:
data = {
    'empid':[101,102,103,104,105,106,107,108],
    'empname':['Raju','Raman',np.nan,'Simran','Yogesh','Ravi','Mahesh','Vikas'],
    'empsal':[24565,78656,36654,87686,13324,np.nan,15263,np.nan]
}

In [64]:
emp = pd.DataFrame(data)

In [65]:
emp

   empid empname   empsal
0    101    Raju  24565.0
1    102   Raman  78656.0
2    103     NaN  36654.0
3    104  Simran  87686.0
4    105  Yogesh  13324.0
5    106    Ravi      NaN
6    107  Mahesh  15263.0
7    108   Vikas      NaN

In [66]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   empid    8 non-null      int64
 1   empname  7 non-null      object
 2   empsal   6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 324.0+ bytes

In [67]:
emp.empsal

0    24565.0
1    78656.0
2    36654.0
3    87686.0
4    13324.0
5        NaN
6    15263.0
7        NaN
Name: empsal, dtype: float64

In [68]:
emp.empsal.sum()

np.float64(256148.0)

In [69]:
emp.empsal.mean()

np.float64(42691.333333333336)

In [70]:
# Check missing value in DataFrame

In [71]:
emp.isnull()

   empid  empname  empsal
0  False    False   False
1  False    False   False
2  False     True   False
3  False    False   False
4  False    False   False
5  False    False    True
6  False    False   False
7  False    False    True

In [72]:
emp.isnull().sum()

empid      0
empname    1
empsal     2
dtype: int64

In [73]:
# Fill Missing Value
emp.fillna(value = 0)

   empid empname   empsal
0    101    Raju  24565.0
1    102   Raman  78656.0
2    103       0  36654.0
3    104  Simran  87686.0
4    105  Yogesh  13324.0
5    106    Ravi      0.0
6    107  Mahesh  15263.0
7    108   Vikas      0.0

In [74]:
emp.fillna('Missing')

   empid  empname   empsal
0    101     Raju  24565.0
1    102    Raman  78656.0
2    103  Missing  36654.0
3    104   Simran  87686.0
4    105   Yogesh  13324.0
5    106     Ravi  Missing
6    107   Mahesh  15263.0
7    108    Vikas  Missing

In [75]:
newemp = emp.copy()

In [76]:
newemp.empsal = newemp.empsal.fillna(value = 5000)

In [77]:
newemp

   empid empname   empsal
0    101    Raju  24565.0
1    102   Raman  78656.0
2    103     NaN  36654.0
3    104  Simran  87686.0
4    105  Yogesh  13324.0
5    106    Ravi   5000.0
6    107  Mahesh  15263.0
7    108   Vikas   5000.0

In [78]:
newemp = emp.copy()

In [79]:
newemp.empsal.mean()

np.float64(42691.333333333336)

In [80]:
newemp

   empid empname   empsal
0    101    Raju  24565.0
1    102   Raman  78656.0
2    103     NaN  36654.0
3    104  Simran  87686.0
4    105  Yogesh  13324.0
5    106    Ravi      NaN
6    107  Mahesh  15263.0
7    108   Vikas      NaN

In [81]:
newemp.empsal = newemp.empsal.fillna( value=42691 )

In [82]:
newemp

   empid empname   empsal
0    101    Raju  24565.0
1    102   Raman  78656.0
2    103     NaN  36654.0
3    104  Simran  87686.0
4    105  Yogesh  13324.0
5    106    Ravi  42691.0
6    107  Mahesh  15263.0
7    108   Vikas  42691.0

In [83]:
newemp.empname = newemp.empname.fillna('Not Found')

In [84]:
newemp

   empid    empname   empsal
0    101       Raju  24565.0
1    102      Raman  78656.0
2    103  Not Found  36654.0
3    104     Simran  87686.0
4    105     Yogesh  13324.0
5    106       Ravi  42691.0
6    107     Mahesh  15263.0
7    108      Vikas  42691.0